---
- name: Copy file
  hosts: all
  tasks: 
  - name: copying file
    copy:
      src: /tmp/filename
      dest: /tmp
      mode: 0777
      group: ansible
      owner: root
  
  - name: install httpd
    yum:
      name: httpd
      state: installed

